In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
test_data = pd.read_csv('../Data/test_data.csv')
test_data = test_data.drop(columns = '表面风化')
test_data = test_data.fillna(value = 0)
test_data

文物编号  二氧化硅(SiO2)  氧化钠(Na2O)  氧化钾(K2O)  氧化钙(CaO)  氧化镁(MgO)  氧化铝(Al2O3)  \
0   A1       78.45        0.0      0.00      6.08      1.86        7.23   
1   A2       37.75        0.0      0.00      7.63      0.00        2.33   
2   A3       31.95        0.0      1.36      7.19      0.81        2.93   
3   A4       35.47        0.0      0.79      2.89      1.05        7.07   
4   A5       64.29        1.2      0.37      1.64      2.34       12.75   
5   A6       93.17        0.0      1.35      0.64      0.21        1.52   
6   A7       90.83        0.0      0.98      1.12      0.00        5.06   
7   A8       51.12        0.0      0.23      0.89      0.00        2.12   

   氧化铁(Fe2O3)  氧化铜(CuO)  氧化铅(PbO)  氧化钡(BaO)  五氧化二磷(P2O5)  氧化锶(SrO)  氧化锡(SnO2)  \
0        2.15      2.11      0.00      0.00         1.06      0.03       0.00   
1        0.00      0.00     34.30      0.00        14.27      0.00       0.00   
2        7.06      0.21     39.58      4.69         2.68      0.52       0.00   
3        6.45      0.96     24.28      8.31         8.45      0.28       0.00   
4        0.81      0.94     12.23      2.16         0.19      0.21       0.49   
5        0.27      1.73      0.00      0.00         0.21      0.00       0.00   
6        0.24      1.17      0.00      0.00         0.13      0.00       0.00   
7        0.00      9.01     21.24     11.34         1.46      0.31       0.00   

   二氧化硫(SO2)  
0       0.51  
1       0.00  
2       0.00  
3       0.00  
4       0.00  
5       0.00  
6       0.11  
7       2.26

Pre-processing test data for Bp

In [3]:
feature_Bp = ['二氧化硅(SiO2)', '氧化钾(K2O)', '氧化钙(CaO)', '氧化铝(Al2O3)',
              '氧化铜(CuO)', '氧化铁(Fe2O3)', '五氧化二磷(P2O5)',  '氧化钠(Na2O)']

Data_for_Bp = test_data[feature_Bp]
Data_for_Bp

二氧化硅(SiO2)  氧化钾(K2O)  氧化钙(CaO)  氧化铝(Al2O3)  氧化铜(CuO)  氧化铁(Fe2O3)  \
0       78.45      0.00      6.08        7.23      2.11        2.15   
1       37.75      0.00      7.63        2.33      0.00        0.00   
2       31.95      1.36      7.19        2.93      0.21        7.06   
3       35.47      0.79      2.89        7.07      0.96        6.45   
4       64.29      0.37      1.64       12.75      0.94        0.81   
5       93.17      1.35      0.64        1.52      1.73        0.27   
6       90.83      0.98      1.12        5.06      1.17        0.24   
7       51.12      0.23      0.89        2.12      9.01        0.00   

   五氧化二磷(P2O5)  氧化钠(Na2O)  
0         1.06        0.0  
1        14.27        0.0  
2         2.68        0.0  
3         8.45        0.0  
4         0.19        1.2  
5         0.21        0.0  
6         0.13        0.0  
7         1.46        0.0

Loading cluster information

In [4]:
Bp_cluster = pd.read_csv('../feature/Bp_cluster_center.csv')
Hp_cluster = pd.read_csv('../feature/Hp_cluster_center.csv')

In [23]:
Bp_cluster

array([[  0.        ,  12.10128297,  23.55765774],
       [  1.        , -23.51355754,  -1.22535263],
       [  2.        ,  17.46030308,  -6.22145082]])

In [24]:
Hp_cluster

array([[  0.        , -14.3093024 ,   0.26437718],
       [  1.        ,  14.37504815,   0.27243426]])

Classifying the test data

In [5]:
from sklearn.decomposition import PCA

pca = PCA(n_components = 2)
X = pca.fit_transform(Data_for_Bp)
X

array([[ 18.0123096 ,  -0.2016463 ],
       [-23.9540111 ,   8.89675443],
       [-28.52569032,  -2.70826632],
       [-25.4637943 ,  -0.96816221],
       [  4.62108939,  -5.92289506],
       [ 33.05758532,   2.74467851],
       [ 30.77243696,   0.91096573],
       [ -8.51992555,  -2.75142879]])

In Bp

In [25]:
Bp_cluster = np.array(Bp_cluster)
Bp_cluster

array([[  0.        ,  12.10128297,  23.55765774],
       [  1.        , -23.51355754,  -1.22535263],
       [  2.        ,  17.46030308,  -6.22145082]])

In [7]:
Bp_class1 = Bp_cluster[0][1 : 2]
Bp_class2 = Bp_cluster[1][1 : 2]
Bp_class3 = Bp_cluster[2][1 : 2]
dist_matrix_Bp = []
for i in range(X.shape[0]):
    point = X[i]
    dist_of_point = []
    dist1 = np.linalg.norm(point - Bp_class1)
    dist_of_point.append(dist1)
    dist2 = np.linalg.norm(point - Bp_class2)
    dist_of_point.append(dist2)
    dist3 = np.linalg.norm(point - Bp_class3)
    dist_of_point.append(dist3)

    dist_matrix_Bp.append(dist_of_point)

dist_matrix_Bp

[[13.649260213021783, 47.62187362391076, 17.670573478144078],
 [36.19742025919274, 32.4133047003701, 42.290421897684446],
 [43.24203635678286, 21.400505086889737, 50.2143682627024],
 [39.773677570011124, 22.629588468854916, 46.712808400968065],
 [19.514719817675374, 33.18116581091978, 26.676194694382175],
 [22.95022124557337, 62.36817429849426, 21.443526289835994],
 [21.76775577318518, 59.527527552284525, 21.238961256748013],
 [25.413328937057347, 25.610056430332428, 32.91635437289738]]

dist_matrix中，第一列为点到第一个cluster的欧式距离，第二列为点到第二个cluster的欧式距离，第三列为点到第三个cluster的欧式距离

In Hp

In [8]:
Hp_cluster = np.array(Hp_cluster)
Hp_cluster

array([[  0.        , -14.3093024 ,   0.26437718],
       [  1.        ,  14.37504815,   0.27243426]])

In [26]:
Hp_class1 = Hp_cluster[0][1 : 2]
Hp_class2 = Hp_cluster[1][1 : 2]
dist_matrix_Hp = []
for i in range(X.shape[0]):
    point = X[i]
    dist_of_point = []
    dist1 = np.linalg.norm(point - Hp_class1)
    dist_of_point.append(dist1)
    dist2 = np.linalg.norm(point - Hp_class2)
    dist_of_point.append(dist2)

    dist_matrix_Hp.append(dist_of_point)

dist_matrix_Hp

[[35.266309179730506, 15.023637770127307],
 [25.13048904603123, 38.718580614062226],
 [18.34910688804675, 46.1769747149018],
 [17.389902565915147, 42.69130440305688],
 [20.7048680664109, 22.519906969259623],
 [50.34342377871922, 22.006878313010915],
 [47.58171693520046, 21.216877134276782],
 [12.926767837654852, 28.591887543186672]]

In [27]:
pd.DataFrame(dist_matrix_Hp).to_excel('../Q3_answer/Q3_1/Hp/dist_matrix_Hp.xlsx')
pd.DataFrame(dist_matrix_Bp).to_excel('../Q3_answer/Q3_1/Pb/dist_matrix_Pb.xlsx')

Sensitive Analysis
我们认为，当距离的平均值距离最小值近，且方差小时，认为该模型灵敏性不高，较为迟钝，反之亦然

In [28]:
dist_matrix_Hp_sa = pd.DataFrame(dist_matrix_Hp)
dist_matrix_Hp_sa

0          1
0  35.266309  15.023638
1  25.130489  38.718581
2  18.349107  46.176975
3  17.389903  42.691304
4  20.704868  22.519907
5  50.343424  22.006878
6  47.581717  21.216877
7  12.926768  28.591888

In [29]:
dist_matrix_Pb_sa = pd.DataFrame(dist_matrix_Bp)
dist_matrix_Pb_sa

0          1          2
0  13.649260  47.621874  17.670573
1  36.197420  32.413305  42.290422
2  43.242036  21.400505  50.214368
3  39.773678  22.629588  46.712808
4  19.514720  33.181166  26.676195
5  22.950221  62.368174  21.443526
6  21.767756  59.527528  21.238961
7  25.413329  25.610056  32.916354

For Hp

In [30]:
dist_matrix_Hp_sa['mean'] = dist_matrix_Hp_sa.apply(lambda x : x.mean(), axis = 1)
dist_matrix_Hp_sa['variance'] = dist_matrix_Hp_sa.apply(lambda x : x.var(), axis = 1)
dist_matrix_Hp_sa['min_value'] = dist_matrix_Hp_sa.apply(lambda x : x.min(), axis = 1)
dist_matrix_Hp_sa

0          1       mean    variance  min_value
0  35.266309  15.023638  25.144973  102.441436  15.023638
1  25.130489  38.718581  31.924535   46.159058  25.130489
2  18.349107  46.176975  32.263041  193.597557  18.349107
3  17.389903  42.691304  30.040603  160.040234  17.389903
4  20.704868  22.519907  21.612388    0.823592   0.823592
5  50.343424  22.006878  36.175151  200.739952  22.006878
6  47.581717  21.216877  34.399297  173.776194  21.216877
7  12.926768  28.591888  20.759328   61.348994  12.926768

For Pb

In [31]:
dist_matrix_Pb_sa['mean'] = dist_matrix_Pb_sa.apply(lambda x : x.mean(), axis = 1)
dist_matrix_Pb_sa['variance'] = dist_matrix_Pb_sa.apply(lambda x : x.var(), axis = 1)
dist_matrix_Pb_sa['min_value'] = dist_matrix_Pb_sa.apply(lambda x : x.min(), axis = 1)
dist_matrix_Pb_sa

0          1          2       mean    variance  min_value
0  13.649260  47.621874  17.670573  26.313902  229.709978  13.649260
1  36.197420  32.413305  42.290422  36.967049   16.555738  16.555738
2  43.242036  21.400505  50.214368  38.285637  150.656068  21.400505
3  39.773678  22.629588  46.712808  36.372025  102.452534  22.629588
4  19.514720  33.181166  26.676195  26.457360   31.152569  19.514720
5  22.950221  62.368174  21.443526  35.587307  358.985774  21.443526
6  21.767756  59.527528  21.238961  34.178082  321.343811  21.238961
7  25.413329  25.610056  32.916354  27.979913   12.190676  12.190676

In [32]:
dist_matrix_Hp_sa.to_excel('../Q3_answer/Q3_2/Hp/dist_Hp_sa.xlsx')
dist_matrix_Pb_sa.to_excel('../Q3_answer/Q3_2/Pb/dist_Pb_sa.xlsx')